version: "3.9"
services:
  api:
    build: ./infra
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./:/app
  web:
    image: node:20
    working_dir: /app/web
    command: bash -lc "npm ci && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
